library(igraph)

pdf(file="./data/out/3/er1.pdf")
net <- sample_gnm(n=100, m=40)
plot(net, vertex.size=6, vertex.label=NA)
write_graph(net, "./data/out/3/er1.txt", "edgelist")
dev.off()
pdf(file="./data/out/3/er1kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/er1dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()

pdf(file="./data/out/3/er2.pdf")
net <- sample_gnm(n=100, m=60)
plot(net, vertex.size=6, vertex.label=NA)
write_graph(net, "./data/out/3/er2.txt", "edgelist")
dev.off()
pdf(file="./data/out/3/er2kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/er2dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()


pdf(file="./data/out/3/er3.pdf")
net <- sample_gnm(n=100, m=90)
plot(net, vertex.size=6, vertex.label=NA)
write_graph(net, "./data/out/3/er3.txt", "edgelist")
dev.off()
pdf(file="./data/out/3/er3kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/er3dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()




pdf(file="./data/out/3/sw1.pdf")
net <- sample_smallworld(dim=2, size=10, nei=1, p=0.1)
write_graph(net, "./data/out/3/sw1.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA, layout=layout_in_circle)
dev.off()
pdf(file="./data/out/3/sw1kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/sw1dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()


pdf(file="./data/out/3/sw2.pdf")
net <- sample_smallworld(dim=2, size=20, nei=1, p=0.1)
write_graph(net, "./data/out/3/sw2.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA, layout=layout_in_circle)
dev.off()
pdf(file="./data/out/3/sw2kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/sw2dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()


pdf(file="./data/out/3/sw3.pdf")
net <- sample_smallworld(dim=2, size=30, nei=1, p=0.1)
write_graph(net, "./data/out/3/sw3.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA, layout=layout_in_circle)
dev.off()
pdf(file="./data/out/3/sw3kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/sw3dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()





pdf(file="./data/out/3/ba1.pdf")
net <- sample_pa(n=100, power=1, m=1, directed=F)
write_graph(net, "./data/out/3/ba1.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA)
dev.off()
pdf(file="./data/out/3/ba1kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/ba1dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()


pdf(file="./data/out/3/ba2.pdf")
net <- sample_pa(n=100, power=2, m=1, directed=F)
write_graph(net, "./data/out/3/ba2.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA)
dev.off()
pdf(file="./data/out/3/ba2kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/ba2dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()

pdf(file="./data/out/3/ba3.pdf")
net <- sample_pa(n=100, power=3, m=1, directed=F)
write_graph(net, "./data/out/3/ba3.txt", "edgelist")
plot(net, vertex.size=6, vertex.label=NA)
dev.off()
pdf(file="./data/out/3/ba3kk.pdf")
l <- layout_with_kk(net)
plot(net, layout=l)
dev.off()
pdf(file="./data/out/3/ba3dist.pdf")
deg <- degree(net, mode="all")
deg.dist <- degree.distribution(net, cumulative=T)
plot(degree.distribution(net, cumulative=T), pch=20,xlab="degree", ylab="cumulative frequency", type="l")
dev.off()